import { Jobs } from '@/types/jobs';
export const mockupJobsList: Jobs[] = [
  {
    id: 1,
    department: 'Development',
    status: 'active',
    salary_range: { min: 8000000, max: 15000000 },
    job_name: 'Frontend Developer',
    job_type: 'full-time',
    job_description:
      'Develop and maintain user-facing features using React and TypeScript. Collaborate with designers and backend developers to deliver a seamless user experience.',
    number_candidates: 12,
    company: 'Rakamin Academy',
    location: 'Jakarta, Indonesia',
    created_date: '2025-10-10',
    profile_configuration: {
      full_name: 'mandatory',
      email: 'mandatory',
      photo_profile: 'mandatory',
      gender: 'optional',
      domicile: 'optional',
      phone: 'optional',
      linkedin: 'off',
      birth: 'optional',
    },
    applicants: [
      {
        id: 1,
        full_name: 'Ayu Putri',
        email: 'ayu.putri@example.com',
        phone: '81298765432',
        country_code: '+62',
        domicile: 'Jakarta',
        gender: 'Female',
        linkedin: 'https://linkedin.com/in/ayuputri',
        birth: '1998-06-12',
      },
      {
        id: 2,
        full_name: 'Rizal Pratama',
        email: 'rizal.pratama@example.com',
        phone: '81377774444',
        country_code: '+62',
        domicile: 'Bandung',
        gender: 'Male',
        linkedin: 'https://linkedin.com/in/rizalpratama',
        birth: '1996-11-04',
      },
    ],
  },
  {
    id: 2,
    department: 'Product Design',
    status: 'active',
    salary_range: { min: 9000000, max: 14000000 },
    job_name: 'UI/UX Designer',
    job_type: 'full-time',
    job_description:
      'Design and optimize user interfaces for both web and mobile platforms. Work closely with product teams to improve usability and engagement.',
    number_candidates: 9,
    company: 'Kreasi Studio',
    location: 'Yogyakarta Indonesia',
    created_date: '2025-09-12',
    profile_configuration: {
      full_name: 'mandatory',
      email: 'mandatory',
      photo_profile: 'mandatory',
      gender: 'optional',
      domicile: 'optional',
      phone: 'optional',
      linkedin: 'off',
      birth: 'optional',
    },
    applicants: [
      {
        id: 1,
        full_name: 'Sinta Maharani',
        email: 'sinta.maharani@example.com',
        phone: '82134567890',
        country_code: '+62',
        domicile: 'Yogyakarta',
        gender: 'Female',
        linkedin: 'https://linkedin.com/in/sintamaharani',
        birth: '1999-03-20',
      },
      {
        id: 2,
        full_name: 'Dwi Nugroho',
        email: 'dwi.nugroho@example.com',
        phone: '82265432109',
        country_code: '+62',
        domicile: 'Surabaya',
        gender: 'Male',
        linkedin: 'https://linkedin.com/in/dwinugroho',
        birth: '1997-08-02',
      },
    ],
  },
  {
    id: 3,
    department: 'Development',
    status: 'draft',
    salary_range: { min: 10000000, max: 18000000 },
    job_name: 'Backend Developer',
    job_type: 'contract',
    job_description:
      'Develop scalable REST APIs and microservices using Node.js and Express. Maintain code quality and ensure system performance.',
    number_candidates: 7,
    company: 'IT Solution',
    location: 'Bandung, Indonesia',
    created_date: '2025-09-25',
    profile_configuration: {
      full_name: 'mandatory',
      email: 'mandatory',
      photo_profile: 'mandatory',
      gender: 'optional',
      domicile: 'optional',
      phone: 'optional',
      linkedin: 'off',
      birth: 'optional',
    },
    applicants: [],
  },
  {
    id: 4,
    department: 'Marketing',
    status: 'inactive',
    salary_range: { min: 7000000, max: 12000000 },
    job_name: 'Digital Marketing Specialist',
    job_type: 'part_time',
    job_description:
      'Plan and execute digital marketing campaigns across multiple channels including SEO, SEM, and social media platforms.',
    number_candidates: 5,
    company: 'Global Marketing Agency',
    location: 'Suraya, Indonesia',
    created_date: '2025-08-30',
    profile_configuration: {
      full_name: 'mandatory',
      email: 'mandatory',
      photo_profile: 'mandatory',
      gender: 'optional',
      domicile: 'optional',
      phone: 'optional',
      linkedin: 'off',
      birth: 'optional',
    },
    applicants: [],
  },
];
